; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.38"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.7"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.4"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[search404][subdir] = "contrib"
projects[search404][version] = "1.3"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.10"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.2"

; Themes
projects[bootstrap][subdir] = "contrib"
projects[bootstrap][version] = "3.0"

; Libraries
libraries[chosen][download][type] = "get"
libraries[chosen][download][url] = "https://github.com/harvesthq/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip"
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"
